name: Update POT
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'locales/**'
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs: 
  run:
    
    name: Update POT
      
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: install xgettext
    
      run: sudo apt-get install gettext;
    - name: Update POT
      run: sh tools/extract_template.sh;


    - name: Commit changes
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
      with:
        message: "Update POT"
    - name: Push changes
 
      uses: actions-go/push@7ad7ce209f2a038e7bca929b7a4c92026363f856
  
